/*
 * generated by Xtext 2.37.0
 */
package uk.ac.kcl.inf.mdd2.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class TurtlesUiModule extends AbstractTurtlesUiModule {
}
