/*
 * generated by Xtext 2.37.0
 */
package uk.ac.kcl.inf.mdd2.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
class TurtlesProposalProvider extends AbstractTurtlesProposalProvider {
}
