/*
 * generated by Xtext 2.37.0
 */
package uk.ac.kcl.inf.mdd2


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class TurtlesRuntimeModule extends AbstractTurtlesRuntimeModule {
}
